// <auto-generated />
using ai_tutor.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace aitutor.Migrations
{
    [DbContext(typeof(AiTutorContext))]
    partial class AiTutorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ai_tutor.Models.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ai_tutor.Models.Lecture", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Courseid");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.HasIndex("Courseid");

                    b.ToTable("Lecture");
                });

            modelBuilder.Entity("ai_tutor.Models.Lecture", b =>
                {
                    b.HasOne("ai_tutor.Models.Course")
                        .WithMany("lectures")
                        .HasForeignKey("Courseid");
                });
#pragma warning restore 612, 618
        }
    }
}
